Repository old-g-moment/organizer, pull requests merged in 2022-04, with the labels that each got.

#2 setup
  packages/backend/README.md
  packages/backend/mvnw
  packages/backend/mvnw.cmd
  packages/backend/pom.xml
  packages/backend/src/main/java/com/oldgmoment/organizer/organizer/BackendApplication.java
  packages/backend/src/main/java/com/oldgmoment/organizer/organizer/Controllers/HelloWorld.java
  packages/backend/src/main/resources/application.properties
  packages/backend/src/test/java/com/oldgmoment/organizer/organizer/BackendApplicationTests.java
Labels: Java

#3 Refactor (Monorepo): Alter configuration of Monorepo
  .gitignore
  lerna.json
  package-lock.json
  package.json
  packages/front/organizer/yarn.lock
  packages/organizer/.eslintrc.json
  packages/organizer/README.md
  packages/organizer/next-env.d.ts
  packages/organizer/next.config.js
  packages/organizer/package.json
  packages/organizer/pages/_app.tsx
  packages/organizer/pages/api/hello.ts
  packages/organizer/pages/index.tsx
  packages/organizer/public/favicon.ico
  packages/organizer/public/vercel.svg
  packages/organizer/styles/Home.module.css
  packages/organizer/styles/globals.css
  packages/organizer/tsconfig.json
  yarn.lock
Labels: enhancement

#4 Refactor (Monorepo): Alter version of main frontend app
  packages/organizer/package.json
Labels: enhancement

#5 ORG-9 | Eslint, prettier and tsconfig file setup
  .eslintrc.json
  .prettierrc.json
  package.json
  packages/organizer/pages/_app.tsx
  packages/organizer/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: configuration

#7 Husky and commitlint with commitizen
  .husky/commit-msg
  .husky/pre-commit
  .lintstagedrc
  commitlint.config.js
  package.json
  packages/organizer/package.json
  yarn.lock
Labels: enhancement
